require 'buildr/scala'
# Generated by Buildr 1.3.4, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "buildr-sandbox"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

desc "The Buildr-sandbox project"
define "buildr-sandbox" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  compile.options.target = '1.5'

  desc "The module A that does not fail on configuration error"
  define "testmodule" do
    test.using :testng
    package :jar
  end

  desc "The module that contains a failing test"
  define "testmodule2" do
    test.using :testng
    package :jar
  end

end
